In [1]:
print(type(...))
print(Ellipsis == ...)
print(...)


<class 'ellipsis'>
True
Ellipsis


In [ ]:
def fun1(): pass
def fun2(): ...


In [2]:
# %pip install numpy
import numpy as np

# arr=np.random.random((2,2,2))
# print(arr)
# print(arr[...,0,0])
a = np.array([[[1, 2, 21], [3, 4, 34]],
              [[5, 6, 56], [7, 8, 78]]])
print("a:", a)
print('a.shape:', a.shape)
print("-"*10)

a: [[[ 1  2 21]
  [ 3  4 34]]

 [[ 5  6 56]
  [ 7  8 78]]]
a.shape: (2, 2, 3)
----------


In [23]:
b = a[..., 0:2]
# 取最后一个维度下标为0-1的数
print('b :', b)
print('shape.b:', b.shape)
print("-"*10)

b : [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape.b: (2, 2, 2)
----------


In [34]:
c = a[..., 1]
# 只取axis2 的第 1 号数据
print("c:", c)
print("c.shape", c.shape)
print("-"*10)

c: [[2 4]
 [6 8]]
c.shape (2, 2)
----------


In [35]:
cx = a[...,2]
# 只取axis2 =2数据 
print("cx:", cx)
print("cx.shape", cx.shape)
print("-"*10)


cx: [[21 34]
 [56 78]]
cx.shape (2, 2)
----------


In [36]:
cmid = a[1,..., 2]
# 只取axis0=1 同时 axis2=2 数据
print("cmid:", cmid)
print("cmid.shape", cmid.shape)
print("-"*10)


cmin: [56 78]
cmin.shape (2,)
----------


In [26]:
c1 = a[1]
# 取0轴 为1的数据
print("c1:", c1)
print("c1.shape", c1.shape)
print("-"*10)


c1: [[ 5  6 56]
 [ 7  8 78]]
c1.shape (2, 3)
----------


In [27]:
c2 = a[-1]
# 取0轴 为-1的数据
print("c2:", c2)
print("c2.shape", c2.shape)
print("-"*10)



c2: [[ 5  6 56]
 [ 7  8 78]]
c2.shape (2, 3)
----------


In [30]:
c3 = a[0]
# 取0轴 为0的数据
print("c3:", c3)
print("c3.shape", c3.shape)
print("-"*10)


c3: [[ 1  2 21]
 [ 3  4 34]]
c3.shape (2, 3)
----------


In [31]:
c4 = a[:,0,:]
# 取1轴 为0的数据
print("c4:", c4)
print("c4.shape", c4.shape)
print("-"*10)


c4: [[ 1  2 21]
 [ 5  6 56]]
c4.shape (2, 3)
----------


In [28]:
d = a[..., 1:2]
#取 axis2 为1-2的 数据
print("d", d)
print("d.shape", d.shape)
print("-"*10)


d [[[2]
  [4]]

 [[6]
  [8]]]
d.shape (2, 2, 1)
----------


In [4]:
x=np.array([[1,2],[3,4],[5,6]])
print(x)
y = x[[0, 1, 2], [0, 1, 0]]  # 去(0,0),(1,1),(2,0)数据
print(y)


[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [11]:
print("len(axis0)",len(a))
print("len(axis1)",len(a[0]))
print("len axis2",len(a[0][0]))
axis0,axis1,axis2=a.shape
print(axis0,axis1,axis2)

len(axis0) 2
len(axis1) 2
len axis2 3
2 2 3


In [19]:
arr_43=np.random.randint(0,9,(4,3))
print(arr_43)

[[7 3 7]
 [3 6 0]
 [6 3 8]
 [3 8 2]]


In [37]:
axis0, axis1 = arr_43.shape
corner4=arr_43[[0,0,axis0-1,axis0-1],[0,axis1-1,0,axis1-1]]
print(corner4)
arr43=arr_43.sum()
print(arr43)

[7 7 3 2]
56


In [42]:
arr_243 = np.random.randint(0, 9, (2,4, 3))
print(arr_243)


[[[3 2 8]
  [8 8 8]
  [4 7 8]
  [0 0 2]]

 [[7 0 4]
  [0 6 4]
  [0 4 3]
  [3 6 0]]]


In [48]:
print(arr_243.mean())
print(arr_243.mean(axis=0))
print(arr_243.mean(axis=1))
print(arr_243.mean(axis=2))


3.9583333333333335
[[5.  1.  6. ]
 [4.  7.  6. ]
 [2.  5.5 5.5]
 [1.5 3.  1. ]]
[[3.75 4.25 6.5 ]
 [2.5  4.   2.75]]
[[4.33333333 8.         6.33333333 0.66666667]
 [3.66666667 3.33333333 2.33333333 3.        ]]
